"""create_first_index

Revision ID: 3f0436a7bc65
Revises: 8dd6149e6a9c
Create Date: 2017-02-27 03:10:24.775429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0436a7bc65'
down_revision = '8dd6149e6a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_credential_user_id'), 'credential', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_created_at'), 'post', ['created_at'], unique=False)
    op.create_index(op.f('ix_post_user_id'), 'post', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_like_liked_at'), 'post_like', ['liked_at'], unique=False)
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_index(op.f('ix_post_like_liked_at'), table_name='post_like')
    op.drop_index(op.f('ix_post_user_id'), table_name='post')
    op.drop_index(op.f('ix_post_created_at'), table_name='post')
    op.drop_index(op.f('ix_credential_user_id'), table_name='credential')
    # ### end Alembic commands ###
